### ISSUE TITLE
Interface for simple objects

### ISSUE THREAD

**Issue by MaxGoryunov** [MaxGoryunov/saving-iterator#45]
Some objects have method `value` without any parameters. It is quite obvious that these methods have the same signature, but different return types. There is a need for a common interface for such objects.

**Comment by 0pdd** [comment]
@MaxGoryunov 2 puzzles [#55](https://github.com/MaxGoryunov/saving-iterator/issues/55), [#56](https://github.com/MaxGoryunov/saving-iterator/issues/56) are still not solved.

**Comment by 0pdd** [comment]
@MaxGoryunov the puzzle [#56](https://github.com/MaxGoryunov/saving-iterator/issues/56) is still not solved; solved: [#55](https://github.com/MaxGoryunov/saving-iterator/issues/55).

**Comment by 0pdd** [comment]
@MaxGoryunov all 2 puzzles are solved here: [#55](https://github.com/MaxGoryunov/saving-iterator/issues/55), [#56](https://github.com/MaxGoryunov/saving-iterator/issues/56).
