### ISSUE TITLE
$this->method() call in SavingIterator

### ISSUE THREAD

**Issue by MaxGoryunov** [MaxGoryunov/saving-iterator#66]
After reducing code duplication there is a self call inside `current` method: `$this->key()`. Call must be reorganised in such a way that it does not self methods.

**Comment by 0pdd** [comment]
@MaxGoryunov 4 puzzles [#82](https://github.com/MaxGoryunov/saving-iterator/issues/82), [#83](https://github.com/MaxGoryunov/saving-iterator/issues/83), [#84](https://github.com/MaxGoryunov/saving-iterator/issues/84), [#85](https://github.com/MaxGoryunov/saving-iterator/issues/85) are still not solved.
