### ISSUE TITLE
Fakes/ classes are not fakes by definition

### ISSUE THREAD

**Issue by MaxGoryunov** [MaxGoryunov/saving-iterator#7]
Classes in fakes/ folder are not fake classes. Fake classes are used for ease of testing. However, the application of current fakes/ classes is much broader. They should be moved to components/ or testing/components/.

**Comment by 0pdd** [comment]
@MaxGoryunov 3 puzzles [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34), [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36) are still not solved.

**Comment by 0pdd** [comment]
@MaxGoryunov 3 puzzles [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36), [#44](https://github.com/MaxGoryunov/saving-iterator/issues/44) are still not solved; solved: [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34).

**Comment by 0pdd** [comment]
@MaxGoryunov 4 puzzles [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36), [#51](https://github.com/MaxGoryunov/saving-iterator/issues/51), [#52](https://github.com/MaxGoryunov/saving-iterator/issues/52) are still not solved; solved: [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34), [#44](https://github.com/MaxGoryunov/saving-iterator/issues/44).

**Comment by 0pdd** [comment]
@MaxGoryunov 3 puzzles [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36), [#51](https://github.com/MaxGoryunov/saving-iterator/issues/51), [#52](https://github.com/MaxGoryunov/saving-iterator/issues/52) are still not solved; solved: [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34), [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#44](https://github.com/MaxGoryunov/saving-iterator/issues/44).

**Comment by 0pdd** [comment]
@MaxGoryunov 2 puzzles [#51](https://github.com/MaxGoryunov/saving-iterator/issues/51), [#52](https://github.com/MaxGoryunov/saving-iterator/issues/52) are still not solved; solved: [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34), [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36), [#44](https://github.com/MaxGoryunov/saving-iterator/issues/44).

**Comment by 0pdd** [comment]
@MaxGoryunov 2 puzzles [#52](https://github.com/MaxGoryunov/saving-iterator/issues/52), [#64](https://github.com/MaxGoryunov/saving-iterator/issues/64) are still not solved; solved: [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34), [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36), [#44](https://github.com/MaxGoryunov/saving-iterator/issues/44), [#51](https://github.com/MaxGoryunov/saving-iterator/issues/51).

**Comment by 0pdd** [comment]
@MaxGoryunov 3 puzzles [#64](https://github.com/MaxGoryunov/saving-iterator/issues/64), [#68](https://github.com/MaxGoryunov/saving-iterator/issues/68), [#69](https://github.com/MaxGoryunov/saving-iterator/issues/69) are still not solved; solved: [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34), [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36), [#44](https://github.com/MaxGoryunov/saving-iterator/issues/44), [#51](https://github.com/MaxGoryunov/saving-iterator/issues/51), [#52](https://github.com/MaxGoryunov/saving-iterator/issues/52).

**Comment by 0pdd** [comment]
@MaxGoryunov 2 puzzles [#68](https://github.com/MaxGoryunov/saving-iterator/issues/68), [#69](https://github.com/MaxGoryunov/saving-iterator/issues/69) are still not solved; solved: [#34](https://github.com/MaxGoryunov/saving-iterator/issues/34), [#35](https://github.com/MaxGoryunov/saving-iterator/issues/35), [#36](https://github.com/MaxGoryunov/saving-iterator/issues/36), [#44](https://github.com/MaxGoryunov/saving-iterator/issues/44), [#51](https://github.com/MaxGoryunov/saving-iterator/issues/51), [#52](https://github.com/MaxGoryunov/saving-iterator/issues/52), [#64](https://github.com/MaxGoryunov/saving-iterator/issues/64).
