### ISSUE TITLE
SavingIterator contains repeated code

### ISSUE THREAD

**Issue by MaxGoryunov** [MaxGoryunov/saving-iterator#8]
Methods `current` and `key` of `SavingIterator` contain repeated code which should be extracted into a separate class.

**Comment by MaxGoryunov** [comment]
test message

**Comment by MaxGoryunov** [comment]
@rultor hello

**Comment by 0pdd** [comment]
@MaxGoryunov the puzzle [#40](https://github.com/MaxGoryunov/saving-iterator/issues/40) is still not solved.

**Comment by 0pdd** [comment]
@MaxGoryunov the puzzle [#48](https://github.com/MaxGoryunov/saving-iterator/issues/48) is still not solved; solved: [#40](https://github.com/MaxGoryunov/saving-iterator/issues/40).

**Comment by 0pdd** [comment]
@MaxGoryunov all 2 puzzles are solved here: [#40](https://github.com/MaxGoryunov/saving-iterator/issues/40), [#48](https://github.com/MaxGoryunov/saving-iterator/issues/48).
